AddressTypeChange for CE Case ceActualResponses Defaulted to Zero
ONSdigital/census-rm-ddl pull request #80
Opened 2020-10-09 12:49 UTC by LeoKHoward

# Motivation and Context
When an AddressTypeChange event occurs where the new address is a CE Case, the ceActualResponses is null rather than 0 

# What has changed
Set column to be not null

# How to test?
Test locally 

# Links
https://trello.com/c/DUgevj8y

2020-10-09 12:49 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [CE case missing ceActualResponses](https://trello.com/c/DUgevj8y/1494-ce-case-missing-ceactualresponses)

2020-10-09 12:55 UTC, NickGrantONS commented on patches/main/3000_alter_ce_actual_responses_to_be_not_null.sql
> +ALTER TABLE casev2.cases ALTER COLUMN ce_actual_responses SET NOT NULL;
you need to patch the data before you alter the table, on the line before. Patch it like this:

`UPDATE casev2.cases SET ce_actual_responses = 0 WHERE ce_actual_responses IS NULL;`

2020-10-09 12:55 UTC, NickGrantONS requested changes
Needs a data patch

2020-10-20 07:01 UTC, NickGrantONS commented on patches/main/3000_alter_ce_actual_responses_to_be_not_null.sql
> +UPDATE casev2.cases SET ce_actual_responses = 0 WHERE ce_actual_responses IS NULL;
what happened to the `alter table` part?

2020-10-20 07:02 UTC, NickGrantONS requested changes
The `alter table` part of this went missing... or maybe it was never there... I can't remember but I'm sure it was there

2020-10-20 07:02 UTC, NickGrantONS commented on patches/main/3000_alter_ce_actual_responses_to_be_not_null.sql
> +UPDATE casev2.cases SET ce_actual_responses = 0 WHERE ce_actual_responses IS NULL;
`ALTER TABLE casev2.cases ALTER COLUMN ce_actual_responses SET NOT NULL;` <--- why was this removed?

2020-10-21 07:01 UTC, NickGrantONS approved these changes
Looks good. ATs passing.

2020-10-21 13:16 UTC, ryangrundy7 approved these changes

2020-10-22 07:36 UTC, merged